swagger: "2.0"

info:
  title: "Fanlens EEV API"
  version: "3.0.0"
  description: "API related to eev activity"

schemes:
  - https

basePath: /v3/eev

securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization-Token
    in: header

security:
  - api_key: []

produces:
  - application/json

paths:
  /token:
    post:
      summary: get a conversation token for eev
      tags: [eev]
      responses:
        200:
          description: A token and associated conversationId
          schema:
            type: object
            required: [token, conversationId]
            properties:
              token:
                type: string
              conversationId:
                type: string
        500:
          description: could not renew or generate token
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      error:
        type: string
