import React from "react";
import Paper from "material-ui/Paper";

const Container = ({children}) => (
  <Paper style={{textAlign: 'justify', padding: '2em'}}>
    {children}
  </Paper>
);

const Terms = () => (
  <Container>
    <h1>Privacy Policy</h1>
    <h2>Changing or Deleting Information</h2>
    <p>
      If you are a registered user of the Site, you may access and update or correct the information you provided
      to us by e-mailing us at info@fanlens.io.
    </p>
    <h2>Security</h2>
    <p>
      Fanlens is very concerned about safeguarding the confidentiality of your personally identifiable information.
      We employ administrative, physical and electronic measures designed to protect your information from
      unauthorized access. We will make any legally-required disclosures of any breach of the security,
      confidentiality, or integrity of your unencrypted electronically stored personal data to you via email or
      conspicuous posting on this Site in the most expedient time possible and without unreasonable delay, consistent
      with (i) the legitimate needs of law enforcement or (ii) any measures necessary to determine the scope of the
      breach and restore the reasonable integrity of the data system.
    </p>
    <h2>Links to Other Websites</h2>
    <p>
      Our Site contains links to other websites. The fact that we link to a website is not an endorsement,
      authorization or representation of our affiliation with that third party. We do not exercise control over third
      party websites. These other websites may place their own cookies or other files on your computer, collect data
      or solicit personally identifiable information from you. Other sites follow different rules regarding the use or
      disclosure of the personally identifiable information you submit to them. We encourage you to read the privacy
      policies or statements of the other websites you visit.
    </p>
    <h2>Our Policy Towards Children</h2>
    <p>
      The Site is not directed to persons under 13. If a parent or guardian becomes aware that his or her child has
      provided us with personally identifiable information without their consent, he or she should contact us
      at info@fanlens.io. We do not knowingly collect personally identifiable information from children under 13. If
      we become aware that a child under 13 has provided us with personal identifiable Information, we will delete
      such information from our files.
    </p>
    <h2>Changes to this Policy</h2>
    <p>
      This Privacy Policy may be updated from time to time for any reason; each version will apply to information
      collected while it was in place. We will notify you of any material changes to our Privacy Policy by posting the
      new Privacy Policy on our Site. You are advised to consult this Privacy Policy regularly for any changes.
    </p>
    <p>This Privacy Policy is effective as of June 1st, 2016.</p>
    <p>If you have any thoughts or questions about this Privacy Policy please send an email to info@fanlens.io.</p>
  </Container>
);

const Notice = () => (
  <Container>
    <h1>Legal Notice</h1>
    <h2>Responsible for Content, Design and Layout:</h2>
    <dl>
      <dt>Fanlens OG</dt>
      <dt>Dorfstraße 17</dt>
      <dt>6121 Baumkirchen</dt>
      <dt>Austria</dt>
    </dl>
    <p>
      E: info {at} fanlens.io
    </p>
    <h2>Disclaimer Google Analytics:</h2>
    <p>
      This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google").
      Google Analytics uses "cookies", which are text files placed on your computer to help the website analyse
      how visitors use the site. The information generated by the cookie about your use of the website
      (including your IP address) will be transmitted to and stored by Google on servers in the United States.
      Google will use this information for the purpose of evaluating your use of the website, compiling reports on
      website activity for website operators and providing other services relating to website activity and internet
      usage.
      Google may also transfer this information to third parties where required to do so by law,
      or where such third parties process the information on Google's behalf.
      Google will not associate your IP address with any other data held by Google.
      You may refuse the use of cookies by selecting the appropriate settings on your browser, however please
      note that if you do this you may not be able to use the full functionality of this website.
      By using this website, you consent to the processing of data about you by Google in the manner
      and for the purposes set out above.
    </p>
  </Container>
);

const Legal = ({messages}) => (
<main id="legal" style={{display: 'flex', flexDirection: 'column', flex: '1 1 auto'}}>
  <div style={{padding: '16px', overflowY: 'scroll'}}>
    <div className="row center-xs" style={{marginBottom: '16px'}}>
      <div className="col-md-9 col-xs-12">
        <Notice/>
      </div>
    </div>
    <div className="row center-xs">
      <div className="col-md-9 col-xs-12">
        <Terms/>
      </div>
    </div>
  </div>
</main>
);


export default Legal;
